# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Bump version codes and name"
  lane :bump_version do |options|
    codes = %w{production beta alpha internal}
    .map { |track| google_play_track_version_codes(
      # json_key_data: get_play_store_json_key,
      track: track,
      package_name: 'com.omelan.cofi',
    ) }
    .flatten
    newest_code = codes.map { |c| c % 10000 }.max
    version_code = newest_code + 3
    set_value_in_build(
      key: 'versionCode',
      value: version_code.to_s,
      app_project_dir: '**/app',
    )
    set_value_in_build(
      key: 'versionCode',
      value: (newest_code + 1).to_s,
      app_project_dir: '**/wearOS',
    )
    if options[:bump_type] != "don't"
        increment_version_name(
          app_project_dir: '**/app',
          bump_type: options[:bump_type],
        )
         increment_version_name(
          app_project_dir: '**/wearOS',
          bump_type: options[:bump_type],
        )
    end
  end

  desc "Prepare changelog"
  lane :prepare_changelog do
    changelog_md_file = File.open("../docs/Changelog.md")
    unreleased_changelog = changelog_md_file.read.split("\n## ")[1].lines[2..-1].join
    UI.important unreleased_changelog
    File.open("metadata/android/en-US/changelogs/default.txt", "w") { |f| f.write unreleased_changelog }

    changelog_md_file = File.open("../docs/Changelog.md")
    new_changelog = changelog_md_file.read
    changelog_md_file.close
    unreleased = " [Unreleased]

### Added

### Changed

### Removed

"
    date = Time.now.strftime("%F")
    versionAndroid = get_version_name(
      app_project_dir: '**/app',
    )
    versionWearOS = get_version_name(
      app_project_dir: '**/wearOS',
    )
    new_changelog["\n## [Unreleased]\n"] = "\n## [#{versionAndroid}|#{versionWearOS}] - #{date}\n"
    File.open("../docs/Changelog.md", "w") { |f| f.write new_changelog.split("\n##").insert(1, unreleased).join("\n##") }
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy_gps do |options|
    gradle(task: "app:licensePlayStoreRelease app:bundlePlayStoreRelease wearOS:licenseRelease wearOS:bundleRelease")
    upload_to_play_store(
      track: options[:prerelease] ? 'internal' : 'production',
      skip_upload_apk: true,
      aab_paths: ["app/build/outputs/bundle/playStoreRelease/app-playStore-release.aab",
      "wearOS/build/outputs/bundle/release/wearOS-release.aab"]
    )
  end

  desc "Upload metadata to Google Play Store"
  lane :meta_gps do
    upload_to_play_store(
      track: 'internal',
      skip_upload_apk: true,
      skip_upload_changelogs: false,
      skip_upload_aab: true,
    )
  end

  desc "Deploy a new version to Github Releases"
  lane :deploy_github do |options|
    gradle(task: "app:licenseFullRelease app:assembleFullRelease app:licensePlayStoreRelease app:assemblePlayStoreRelease wearOS:licenseRelease wearOS:assembleRelease")
    versionName = get_version_name(
      app_project_dir: '**/app',
    )
    set_github_release(
      repository_name: "rozPierog/Cofi",
      api_token: ENV["GITHUB_TOKEN_COFI"],
      name: "Cofi " + versionName,
      tag_name: "v" + versionName,
      is_prerelease: options[:prerelease],
      description: (File.read("metadata/android/en-US/changelogs/default.txt") rescue "No changelog provided"),
      # commitish: "master",
      upload_assets: ["app/build/outputs/apk/full/release/app-full-release.apk",
       "app/build/outputs/apk/playStore/release/app-playStore-release.apk",
       "wearOS/build/outputs/apk/release/wearOS-release.apk"]
    )
  end

  desc "Builds an Instant App"
  lane :build_instant do
    gradle(task: "app:licenseInstantRelease app:bundleInstantRelease")
    UI.important "⚠️ Fastlane does not support uploading instant apps to google play console ⚠️"
    UI.important "⚠️ Remember to upload instant app bundle to Play Console! ⚠️"
    sh("open", "../app/build/outputs/bundle/instantRelease")
  end

  lane :create_screenshots do
      `cd .. && ./bin/createScreenshots`
  end

  desc "Perform deploy for all"
  lane :deploy do
    bump_type = UI.select "How to bump version:", %w{major minor patch don't}
    prerelease = prompt(
      text: "is this a prerelease: ",
      boolean: true
    )
    test
    create_screenshots
    bump_version(bump_type: bump_type)
    if bump_type != "don't"
        prepare_changelog
    end
    git_commit(path: ["./*.gradle"], message: "Prepare for release")
    push_to_git_remote
    gradle(task: "clean")
    deploy_github(prerelease: prerelease)
    deploy_gps(prerelease: prerelease)
    build_instant
  end
end
