# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Generate licenses"
  lane :licenses do
    gradle(task: "licenseFullReleaseReport")
  end

  desc "Bump version codes and name"
  lane :bump_version do |options|
    codes = %w{production beta alpha internal}
    .map { |track| google_play_track_version_codes(
      # json_key_data: get_play_store_json_key,
      track: track,
      package_name: 'com.omelan.cofi',
    ) }
    .flatten
    newest_code = codes.map { |c| c % 10000 }.max
    version_code = newest_code + 2
    set_value_in_build(
      key: 'versionCode',
      value: version_code.to_s,
      app_project_dir: '**/app',
    )
    increment_version_name(
      app_project_dir: '**/app',
      bump_type: options[:bump_type],
    )
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy_gps do |options|
    gradle(task: "clean bundleFullRelease")
    upload_to_play_store(
      track: options[:prerelease] ? 'internal' : 'production',
    )
  end

  desc "Upload metadata to Google Play Store"
  lane :meta_gps do
    upload_to_play_store(
      track: 'internal',
      skip_upload_apk: true,
      skip_upload_changelogs: true,
      skip_upload_aab: true,
    )
  end

  desc "Deploy a new version to Github Releases"
  lane :deploy_github do |options|
    gradle(task: "clean assembleFullRelease")
    versionName = get_version_name(
      app_project_dir: '**/app',
    )
    set_github_release(
      repository_name: "rozPierog/Cofi",
      api_token: ENV["GITHUB_TOKEN_COFI"],
      name: "Cofi " + versionName,
      tag_name: "v" + versionName,
      is_prerelease: options[:prerelease],
      description: (File.read("fastlane/metadata/android/release_notes.txt") rescue "No changelog provided"),
      # commitish: "master",
      upload_assets: ["app/build/outputs/apk/full/release/app-full-release.apk"]
    )
  end

  desc "Builds an Instant App"
  lane :build_instant do
    gradle(task: "clean bundleInstantRelease")
    UI.important "⚠️ Fastlane does not support uploading instant apps to google play console ⚠️"
    UI.important "⚠️ Remember to upload instant app bundle to Play Console! ⚠️"
  end

  desc "Perform deploy for all"
  lane :deploy do
    bump_type = UI.select "How to bump version:", %w{major minor patch}
    prerelease = prompt(
      text: "is this a prerelease: ",
      boolean: true
    )
    test
    licenses
    bump_version(bump_type: bump_type)
    git_commit(path: ["./*.gradle"], message: "Version bump")
    push_to_git_remote
    deploy_gps(prerelease: prerelease)
    deploy_github(prerelease: prerelease)
    build_instant
  end
end
