# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy_gps do
    codes = %w{production beta alpha internal}
      .map { |track| google_play_track_version_codes(
        # json_key_data: get_play_store_json_key,
        track: track,
        package_name: 'com.omelan.cofi',
      ) }
      .flatten
    newest_code = codes.map { |c| c % 10000 }.max
    version_code = newest_code + 2
    set_value_in_build(
      key: 'versionCode',
      value: version_code.to_s,
      app_project_dir: '**/app',
    )
    increment_version_name(
      app_project_dir: '**/app',
      bump_type: 'minor',
    )
    gradle(task: "clean licenseFullReleaseReport")
    gradle(task: "clean bundleFullRelease")
    upload_to_play_store(
      track: 'internal',
    )
  end

  desc "Deploy a new version to Github Releases"
  lane :deploy_github do
    gradle(task: "clean assembleFullRelease")
    versionName = get_version_name(
      app_project_dir: '**/app',
    )
    set_github_release(
      repository_name: "rozPierog/Cofi",
      api_token: ENV["GITHUB_TOKEN_COFI"],
      name: "Cofi " + versionName,
      tag_name: "v" + versionName,
      is_prerelease: true,
      description: (File.read("fastlane/metadata/android/release_notes.txt") rescue "No changelog provided"),
      # commitish: "master",
      upload_assets: ["app/build/outputs/apk/full/release/app-full-release.apk"]
    )
  end

  desc "Perform deploy for all"
  lane :deploy do
    test
    deploy_gps
    deploy_github
  end
end
